
<?= $this->extend('common/layout') ?>

<?= $this->section('content') ?>

<?= $this->include('common/header') ?> 

<main role="main">
    <div class="container">
        <h4 class="display-4" style="margin-top: 100px">Terms Of Use</h4>
        
        <span class="d-block p-2 bg-dark text-white">Contract</span>
        <p class="font-weight-light">By using or visiting website, mobile applications, software, data feeds, and services provided to you (collectively the "Service" ) you signify your agreement to these terms and conditions (the "Terms of Service") and privacy policy (the "Privacy Policy" ) of the Company. If you do not agree to any of these terms, please do not use the Service.

        Welcome to easybhk.com! We are a digital real estate advertising / marketing and information services platform connecting people with the real estate market. easybhk.com and our subsidiaries and affiliates (collectively the "Company" or "easybhk.com" ) provide you with access to a variety of services, including but not limited to the <?= base_url();?> website (the "Website" ) and easybhk.com's mobile applications (the "Mobile App" ) and all the products and services available through our Website and Mobile App (collectively the "Services"). The Website and Mobile App is owned and operated by easybhk.com Private Limited, a company incorporated under the laws of India.

        This document and the Privacy Policy is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. These terms of use constitute an electronic record within the meaning of the applicable law. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
        
        <div class="d-flex p-2 bd-highlight">To whom does this policy apply ?</div>
         <p class="font-weight-light">Some parts of this Policy are directed at specific types of people. We use some special terminology to refer to them, which we define below. This Policy applies to everyone who uses our Services, but sometimes we direct parts of it toward particular groups of users.
          Users: "Users" are everyone who uses our Services.

          Real Estate Professionals (REPs): "Real Estate Professionals," or "REPs" are users who have created accounts (free or paid) with us to avail our advertising services, and avail our other Services that we direct towards the professional real estate community. REPs include landlords, agents, developers, institutional property consultants, mortgage professionals and other service providers.</p>

        <div class="d-flex p-2 bd-highlight">What information do we collect, and where do we get it from</div> 
         <p class="font-weight-light">We collect information from everyone who uses our Services: Like many online services, we use technologies like session and persistent cookies, web beacons (tiny image files on web pages that communicate information about the page viewer to the beacon owner), log data, and third-party analytics services to collect and analyze information about all users of our Services. This includes things like User search preferences, interaction with ads on our Services, and location.

          Our servers automatically record information ("Log Data") created by your use of the Services. Log Data may include information such as your IP address, browser type, operating system, the referring web page, pages visited, location, your mobile carrier, device, search terms, and cookie information. We receive Log Data when you interact with our Services, for example, when you visit our Website and / or Mobile App, sign into our Services, or interact with our email notifications. We use Log Data to provide our Services and to measure, customize, and improve them, as well as collect and use them in the aggregate. This policy does not apply to, nor do we take any responsibility for any information that is collected by any third party either using the Services or through any links on the Website and / or Mobile App or through any of the advertisements.

          Cookies are small data files that we transfer to your computer. We use "session" cookies to keep you logged in while you use our Services, to better understand how you interact with our Services, and to monitor aggregate usage and web traffic information on our Services. We use "persistent" cookies to recognize you each time you return to our Services. For example, we create a persistent cookie that includes some basic information about you, like your most recent search and whether an agent responded to a query you sent using easybhk.com's Services. We use this persistent cookie to remember your preferences and, if you create an account, to make your user experience consistent after you register.

          Most internet browsers automatically accept cookies, but you can change your settings or use third-party tools to refuse cookies or prompt you before accepting cookies from the websites you visit. You can also use your browser settings or other tools to delete cookies you already have. Please be aware that some parts of our Services may not work for you if you disable cookies.

          Information we collect from REPs: If you create a REP account with us, whether as a landlord, agent, developer or other service provider, we will ask you to provide certain information in order to set up your account. We ask all REPs to provide details including but not limited to your name, your company name (if available), phone number, email address and details of the property to be uploaded on the Website etc. If you create a paid REP account and become a subscriber, we require you to submit all of the information including but not limited to as required from landlords and agents as well as a description of your campaign and/or your property details. We may also collect financial data like credit card information and billing addresses from subscribers, so that we can process the billing as per the choice of your product and services you subscribe. A easybhk.com representative may call you to verify your information.

          Additional information about you that we obtain from third parties: We may sometimes obtain information about you from third parties and use it to serve you better. For example, our partners may help us provide predictions of your income range and how likely you may be to purchase a home. We will share this augmented data only with selected REPs (subscribers) who you choose to share information with by contacting them through the easybhk.com Services.

          Location Data: If you provide location information (like a ZIP code, street address, or even just a city) during the registration process or at any other time via your account settings, we will store that information and associate it with your account. We may use and store information about your location to provide localized features, to analyze our Services with the help of third-party analytics services, to provide you with relevant advertising and marketing recommendations, and otherwise to improve and customize our Services.</p>  

          <div class="d-flex p-2 bd-highlight">Why we collect information from you</div>
         <p class="font-weight-light">PropertyRaja.com provides digital real estate advertising / marketing and information services through its Website, Mobile App and other services. To provide our Services, we use the information we collect to:

          Help you find the most relevant information for your situation by customizing our Services to optimize your experience.

          Keep you connected with easybhk.com across the internet and update you with residential real estate-related news and information.

          Put you in touch with the right people to sell, buy, rent, or research residential real estate, obtain a mortgage, avail related services and to optimize the information we share with those parties to initiate a productive and efficient relationship.</p>
   </div>
</main>


<?= $this->include('common/footer') ?>
<?= $this->endSection() ?>